export const TableDataLists = [
  {
    STT: 1,
    MaPhieu: "NSDTMB202301",
    Nam: "2023",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "20/12/2022",
    TrangThai: "Mới tạo",
    TrangThaiToTrinh: " ",
    Action: " ",
  },
  {
    STT: 2,
    MaPhieu: "NSDTMB202201",
    Nam: "2022",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "20/10/2022",
    TrangThai: "Chờ soát xét",
    TrangThaiToTrinh: " ",
    Action: " ",
  },
  {
    STT: 3,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
    Action: " ",
  },
];
