export const TableDataLists = [
  {
    STT: 1,
    MaPhieu: "NSDTMB202301",
    Nam: "2023",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "20/12/2022",
    TrangThai: "Mới tạo",
    TrangThaiToTrinh: " ",
  },
  {
    STT: 2,
    MaPhieu: "NSDTMB202201",
    Nam: "2022",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "20/10/2022",
    TrangThai: "Chờ soát xét",
    TrangThaiToTrinh: " ",
  },
  {
    STT: 3,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 4,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 5,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 6,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 7,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 8,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 9,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 10,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 11,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 12,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 13,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 14,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 15,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 16,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 17,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 18,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 19,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 20,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 21,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 22,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 23,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 24,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 25,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 26,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 27,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 28,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 29,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
  {
    STT: 30,
    MaPhieu: "NSDTMB202101",
    Nam: "2021",
    CompanyCode: "DTMB",
    PhongBan: "Đầu tư Miền Bắc",
    NguoiTao: "nhd21",
    NgayTao: "10/11/2022",
    TrangThai: "Ban hành",
    TrangThaiToTrinh: "Đã duyệt",
  },
];
